# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# workflow name
name: Node.js CI
# actions to run workflow
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
# define autonomous tasks
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4 # checkout code
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # setup node
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci # clean install: auto update to latest version of package, not affect to package.json
      - run: npm run build --if-present
      - run: npm test
